name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-x86_64:
    name: Build x86_64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash -ex ci/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: x86_64
          path: bluenebula-auth*

  build-i386:
    name: Build i386
    runs-on: ubuntu-latest
    env:
      ARCH: i386
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: bash -ex ci/build.sh
      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: i386
          path: bluenebula-auth*

  upload:
    name: Create release and upload artifacts
    needs:
      - build-x86_64
      - build-i386
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v2
      - name: Inspect directory after downloading artifacts
        run: ls -alFR
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
            chmod +x pyuploadtool-x86_64.AppImage
            ./pyuploadtool-x86_64.AppImage **/bluenebula-auth*
